// Bakes OSRM road geometry into the app and seeds PostGIS for GeoServer.
//
//   dart run tool/generate_geodata.dart [OSRM_URL]
//
// Writes:
//   lib/shared/map/generated/geo_snapshot.g.dart  — highway lines + trip
//       routes/detour used offline and before live routing responds
//   backend/geoserver/sql/02_seed.sql             — the same geometry and the
//       app's demo incidents / zones / fleet for the GeoServer layers
//
// Re-run after changing NerGeo waypoints, zones or the trip scenarios.
// Default OSRM is the public demo server (~1 req/s, ~30 requests total).

import 'dart:io';

import 'package:ner_logistics/services/geo/geo_math.dart';
import 'package:ner_logistics/services/routing/osrm_client.dart';
import 'package:ner_logistics/shared/map/map_models.dart';
import 'package:ner_logistics/shared/map/ner_geo.dart';

const _highwayToleranceM = 25.0;

Future<void> main(List<String> args) async {
  final osrmUrl = args.isNotEmpty ? args.first : 'https://router.project-osrm.org';
  final osrm = OsrmClient(baseUrl: osrmUrl);
  stdout.writeln('OSRM: $osrmUrl');

  final highways = <String, String>{};
  for (final e in NerGeo.highwayWaypoints.entries) {
    final r = (await osrm.route(e.value, steps: false)).first;
    final line = GeoMath.simplify(r.geometry, _highwayToleranceM);
    highways[e.key] = GeoMath.encodePolyline(line);
    stdout.writeln('  ${e.key.padRight(7)} ${(r.distanceM / 1000).toStringAsFixed(1)} km'
        '  ${r.geometry.length} → ${line.length} pts');
  }

  osrm.close();

  final snapshot = StringBuffer()
    ..writeln('// GENERATED by tool/generate_geodata.dart — do not edit by hand.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln("const kSnapshotGeneratedAt = '${DateTime.now().toUtc().toIso8601String()}';")
    ..writeln("const kSnapshotOsrmUrl = '$osrmUrl';")
    ..writeln()
    ..writeln('const Map<String, String> kHighwayPolylines = {');
  for (final e in highways.entries) {
    snapshot.writeln("  '${e.key}': r'${e.value}',");
  }
  snapshot
    ..writeln('};');
  File('lib/shared/map/generated/geo_snapshot.g.dart')
      .writeAsStringSync(snapshot.toString());

  File('backend/geoserver/sql/02_seed.sql').writeAsStringSync(_seedSql(highways));
  stdout.writeln('Wrote geo_snapshot.g.dart and 02_seed.sql');
}

String _q(String s) => "'${s.replaceAll("'", "''")}'";
String _pt(double lat, double lng) => 'ST_SetSRID(ST_MakePoint($lng, $lat), 4326)';

String _seedSql(Map<String, String> highways) {
  final b = StringBuffer()
    ..writeln('-- GENERATED by tool/generate_geodata.dart — do not edit by hand.')
    ..writeln('-- Highway geometry mirroring the app (lib/shared/map/ner_geo.dart). Incidents, vehicles,')
    ..writeln('-- risk zones, safe zones and depots are not seeded: there is no sample data.')
    ..writeln()
    ..writeln('TRUNCATE ner.highways, ner.incidents, ner.risk_zones, ner.safe_zones, ner.depots, ner.vehicles RESTART IDENTITY;')
    ..writeln();

  for (final e in highways.entries) {
    b.writeln('INSERT INTO ner.highways (highway_id, geom) VALUES '
        '(${_q(e.key)}, ST_SetSRID(ST_LineFromEncodedPolyline(${_q(e.value)}, 6), 4326));');
  }
  b.writeln();

  // Circles become 32-sided polygons; local analytics use the same circles.
  for (final z in [...NerGeo.floodZones, ...NerGeo.landslideZones]) {
    b.writeln('INSERT INTO ner.risk_zones (kind, name, susceptibility, source, geom) VALUES '
        '(${_q(z.kind.name)}, ${_q(z.label)}, ${_q(z.kind == MapZoneKind.landslide ? 'high' : 'moderate')}, '
        "'demo', ST_Buffer(${_pt(z.center.latitude, z.center.longitude)}::geography, ${z.radiusMeters}, 'quad_segs=8')::geometry);");
  }
  b.writeln();

  for (final z in NerGeo.safeZones) {
    b.writeln('INSERT INTO ner.safe_zones (name, radius_m, geom) VALUES '
        '(${_q(z.label)}, ${z.radiusMeters}, ${_pt(z.center.latitude, z.center.longitude)});');
  }
  for (final p in NerGeo.infrastructure) {
    b.writeln('INSERT INTO ner.depots (name, kind, geom) VALUES '
        '(${_q(p.label)}, ${_q(p.kind.name)}, ${_pt(p.point.latitude, p.point.longitude)});');
  }
  b.writeln();

  return b.toString();
}
