/* Geographic reference data for the North Eastern Region.
   Place coordinates are city centres; corridor paths are OSRM road
   geometry generated by ner_logistics/backend/osrm/seed_routes.py. */

import { CORRIDOR_POLYLINES } from './corridors.generated';

export type LatLng = [number, number];

export const NER_CENTER: LatLng = [26.2, 92.9];
export const NER_ZOOM = 6;

export const PLACES: Record<string, LatLng> = {
  guwahati: [26.1445, 91.7362],
  kamrup: [26.1445, 91.7362],
  dimapur: [25.9063, 93.7276],
  kohima: [25.6751, 94.1086],
  imphal: [24.817, 93.9368],
  shillong: [25.5788, 91.8933],
  aizawl: [23.7271, 92.7176],
  agartala: [23.8315, 91.2868],
  itanagar: [27.0844, 93.6053],
  gangtok: [27.3389, 88.6065],
  silchar: [24.8333, 92.7789],
  cachar: [24.8333, 92.7789],
  tezpur: [26.6528, 92.7926],
  sonitpur: [26.6528, 92.7926],
  jorhat: [26.7509, 94.2037],
  dibrugarh: [27.4728, 94.912],
  nagaon: [26.348, 92.6838],
  barpeta: [26.3226, 91.006],
  bongaigaon: [26.4831, 90.5627],
  tawang: [27.5859, 91.8594],
  bomdila: [27.2645, 92.4159],
  siliguri: [26.7271, 88.3953],
  rangpo: [27.176, 88.53],
  lunglei: [22.8671, 92.7655],
  kolasib: [24.2244, 92.6763],
  jiribam: [24.8055, 93.1128],
  senapati: [25.2677, 94.02],
  'mao gate': [25.5167, 94.1333],
  haflong: [25.1686, 93.0167],
  lumding: [25.7502, 93.1712],
  chumoukedima: [25.7962, 93.7806],
  mokokchung: [26.3265, 94.5248],
  wokha: [26.1003, 94.2626],
};

/** Highway corridors: OSRM road geometry, same as public.routes (see corridors.generated.ts). */
export const CORRIDORS: Record<string, { name: string; path: LatLng[] }> = Object.fromEntries(
  Object.entries(CORRIDOR_POLYLINES).map(([id, c]) => [id, { name: c.name, path: decodePolyline(c.polyline6) }]),
);

/** Google encoded polyline, precision 6 (OSRM `polyline6`). */
export function decodePolyline(s: string, precision = 6): LatLng[] {
  const f = 10 ** precision, out: LatLng[] = [];
  let i = 0, lat = 0, lng = 0;
  while (i < s.length) {
    for (const which of [0, 1]) {
      let shift = 0, result = 0, byte: number;
      do {
        byte = s.charCodeAt(i++) - 63;
        result |= (byte & 0x1f) << shift;
        shift += 5;
      } while (byte >= 0x20);
      const delta = result & 1 ? ~(result >> 1) : result >> 1;
      if (which === 0) lat += delta; else lng += delta;
    }
    out.push([lat / f, lng / f]);
  }
  return out;
}

/** "nh 29", "NH29", "nh-29 " → "NH-29" */
export function normalizeRouteId(value: string): string {
  const match = value.trim().match(/^nh[\s-]*(\d+[a-z]?)$/i);
  return match ? `NH-${match[1].toUpperCase()}` : value.trim().toUpperCase();
}

export function corridorFor(routeId: string) {
  return CORRIDORS[normalizeRouteId(routeId)] ?? null;
}

/** Parses "26.3219° N, 91.0013° E" or "26.3219, 91.0013". */
export function parseCoords(value: string | null | undefined): LatLng | null {
  if (!value) return null;
  const match = value.match(/(-?\d+(?:\.\d+)?)\s*°?\s*([NS])?\s*(?:,|\s)\s*(-?\d+(?:\.\d+)?)\s*°?\s*([EW])?/i);
  if (!match) return null;
  let lat = parseFloat(match[1]);
  let lng = parseFloat(match[3]);
  if (match[2]?.toUpperCase() === 'S') lat = -Math.abs(lat);
  if (match[4]?.toUpperCase() === 'W') lng = -Math.abs(lng);
  if (Math.abs(lat) > 90 || Math.abs(lng) > 180) return null;
  return [lat, lng];
}

export function formatCoords([lat, lng]: LatLng): string {
  return `${Math.abs(lat).toFixed(6)}° ${lat >= 0 ? 'N' : 'S'}, ${Math.abs(lng).toFixed(6)}° ${lng >= 0 ? 'E' : 'W'}`;
}

/** Finds the first known place mentioned in free text, e.g. "Barpeta, Assam". */
export function placeFor(text: string | null | undefined): LatLng | null {
  if (!text) return null;
  const lower = text.toLowerCase();
  const key = Object.keys(PLACES).find(name => lower.includes(name));
  return key ? PLACES[key] : null;
}

function corridorMidpoint(routeId: string): LatLng | null {
  const corridor = corridorFor(routeId);
  return corridor ? corridor.path[Math.floor(corridor.path.length / 2)] : null;
}

/** Best available position: captured GPS, then a named place, then the route's midpoint. */
export function locate(item: { gpsCoords?: string; location?: string; route?: string }): LatLng | null {
  return parseCoords(item.gpsCoords) ?? placeFor(item.location) ?? (item.route ? corridorMidpoint(item.route) : null);
}
