-- Assistant audit log (supabase/functions/chat). Also the rate-limit counter: chat_quota_ok()
-- counts the caller's rows in the last hour. Written by the function as the caller, so RLS
-- pins every row to auth.uid(). No update/delete for clients, or a user could reset their quota.

create table public.chat_logs (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null default auth.uid() references auth.users on delete cascade,
  role       text,
  prompt     text,
  response   text,
  tools      text[],
  tokens_in  integer,
  tokens_out integer,
  created_at timestamptz not null default now()
);
create index chat_logs_user_created_idx on public.chat_logs (user_id, created_at desc);

alter table public.chat_logs enable row level security;

create policy chat_logs_insert_own on public.chat_logs for insert to authenticated
  with check (user_id = (select auth.uid()));
create policy chat_logs_select on public.chat_logs for select to authenticated
  using (user_id = (select auth.uid()) or public.has_role('control_room'));

grant select, insert on public.chat_logs to authenticated;
revoke update, delete on public.chat_logs from authenticated;

-- ponytail: rows are written when a stream finishes, so parallel in-flight requests can overshoot
-- the limit by a few. Fine for a per-user fuse; count at request start if abuse appears.
create function public.chat_quota_ok(p_limit integer default 30) returns boolean
language sql stable security definer set search_path = '' as $$
  select count(*) < least(greatest(coalesce(p_limit, 30), 1), 200)
  from public.chat_logs
  where user_id = auth.uid() and created_at > now() - interval '1 hour'
$$;
revoke execute on function public.chat_quota_ok(integer) from public, anon;
grant execute on function public.chat_quota_ok(integer) to authenticated;
