-- NE India states and districts (from northeast_india_districts.csv). Coordinates are not included;
-- add locations.geom to enable the ML "near place" lookup.
insert into public.locations (name, district, state, kind) values
  ('Arunachal Pradesh', null, 'Arunachal Pradesh', 'state'),
  ('Assam', null, 'Assam', 'state'),
  ('Manipur', null, 'Manipur', 'state'),
  ('Meghalaya', null, 'Meghalaya', 'state'),
  ('Mizoram', null, 'Mizoram', 'state'),
  ('Nagaland', null, 'Nagaland', 'state'),
  ('Tripura', null, 'Tripura', 'state'),
  ('Sikkim', null, 'Sikkim', 'state'),
  ('Anjaw', 'Anjaw', 'Arunachal Pradesh', 'district'),
  ('Bichom', 'Bichom', 'Arunachal Pradesh', 'district'),
  ('Changlang', 'Changlang', 'Arunachal Pradesh', 'district'),
  ('Dibang Valley', 'Dibang Valley', 'Arunachal Pradesh', 'district'),
  ('East Kameng', 'East Kameng', 'Arunachal Pradesh', 'district'),
  ('East Siang', 'East Siang', 'Arunachal Pradesh', 'district'),
  ('Kamle', 'Kamle', 'Arunachal Pradesh', 'district'),
  ('Keyi Panyor', 'Keyi Panyor', 'Arunachal Pradesh', 'district'),
  ('Kra Daadi', 'Kra Daadi', 'Arunachal Pradesh', 'district'),
  ('Kurung Kumey', 'Kurung Kumey', 'Arunachal Pradesh', 'district'),
  ('Lepa Rada', 'Lepa Rada', 'Arunachal Pradesh', 'district'),
  ('Lohit', 'Lohit', 'Arunachal Pradesh', 'district'),
  ('Longding', 'Longding', 'Arunachal Pradesh', 'district'),
  ('Lower Dibang Valley', 'Lower Dibang Valley', 'Arunachal Pradesh', 'district'),
  ('Lower Siang', 'Lower Siang', 'Arunachal Pradesh', 'district'),
  ('Lower Subansiri', 'Lower Subansiri', 'Arunachal Pradesh', 'district'),
  ('Namsai', 'Namsai', 'Arunachal Pradesh', 'district'),
  ('Pakke-Kessang', 'Pakke-Kessang', 'Arunachal Pradesh', 'district'),
  ('Papum Pare', 'Papum Pare', 'Arunachal Pradesh', 'district'),
  ('Shi Yomi', 'Shi Yomi', 'Arunachal Pradesh', 'district'),
  ('Siang', 'Siang', 'Arunachal Pradesh', 'district'),
  ('Tawang', 'Tawang', 'Arunachal Pradesh', 'district'),
  ('Tirap', 'Tirap', 'Arunachal Pradesh', 'district'),
  ('Upper Siang', 'Upper Siang', 'Arunachal Pradesh', 'district'),
  ('Upper Subansiri', 'Upper Subansiri', 'Arunachal Pradesh', 'district'),
  ('West Kameng', 'West Kameng', 'Arunachal Pradesh', 'district'),
  ('West Siang', 'West Siang', 'Arunachal Pradesh', 'district'),
  ('Itanagar Capital Complex', 'Itanagar Capital Complex', 'Arunachal Pradesh', 'district'),
  ('Baksa', 'Baksa', 'Assam', 'district'),
  ('Bajali', 'Bajali', 'Assam', 'district'),
  ('Barpeta', 'Barpeta', 'Assam', 'district'),
  ('Biswanath', 'Biswanath', 'Assam', 'district'),
  ('Bongaigaon', 'Bongaigaon', 'Assam', 'district'),
  ('Cachar', 'Cachar', 'Assam', 'district'),
  ('Charaideo', 'Charaideo', 'Assam', 'district'),
  ('Chirang', 'Chirang', 'Assam', 'district'),
  ('Darrang', 'Darrang', 'Assam', 'district'),
  ('Dhemaji', 'Dhemaji', 'Assam', 'district'),
  ('Dhubri', 'Dhubri', 'Assam', 'district'),
  ('Dibrugarh', 'Dibrugarh', 'Assam', 'district'),
  ('Dima Hasao', 'Dima Hasao', 'Assam', 'district'),
  ('Goalpara', 'Goalpara', 'Assam', 'district'),
  ('Golaghat', 'Golaghat', 'Assam', 'district'),
  ('Hailakandi', 'Hailakandi', 'Assam', 'district'),
  ('Hojai', 'Hojai', 'Assam', 'district'),
  ('Jorhat', 'Jorhat', 'Assam', 'district'),
  ('Kamrup', 'Kamrup', 'Assam', 'district'),
  ('Kamrup Metropolitan', 'Kamrup Metropolitan', 'Assam', 'district'),
  ('Karbi Anglong', 'Karbi Anglong', 'Assam', 'district'),
  ('Kokrajhar', 'Kokrajhar', 'Assam', 'district'),
  ('Lakhimpur', 'Lakhimpur', 'Assam', 'district'),
  ('Majuli', 'Majuli', 'Assam', 'district'),
  ('Morigaon', 'Morigaon', 'Assam', 'district'),
  ('Nagaon', 'Nagaon', 'Assam', 'district'),
  ('Nalbari', 'Nalbari', 'Assam', 'district'),
  ('Sivasagar', 'Sivasagar', 'Assam', 'district'),
  ('Sonitpur', 'Sonitpur', 'Assam', 'district'),
  ('South Salmara-Mankachar', 'South Salmara-Mankachar', 'Assam', 'district'),
  ('Sribhumi', 'Sribhumi', 'Assam', 'district'),
  ('Tamulpur', 'Tamulpur', 'Assam', 'district'),
  ('Tinsukia', 'Tinsukia', 'Assam', 'district'),
  ('Udalguri', 'Udalguri', 'Assam', 'district'),
  ('West Karbi Anglong', 'West Karbi Anglong', 'Assam', 'district'),
  ('Bishnupur', 'Bishnupur', 'Manipur', 'district'),
  ('Chandel', 'Chandel', 'Manipur', 'district'),
  ('Churachandpur', 'Churachandpur', 'Manipur', 'district'),
  ('Imphal East', 'Imphal East', 'Manipur', 'district'),
  ('Imphal West', 'Imphal West', 'Manipur', 'district'),
  ('Jiribam', 'Jiribam', 'Manipur', 'district'),
  ('Kakching', 'Kakching', 'Manipur', 'district'),
  ('Kamjong', 'Kamjong', 'Manipur', 'district'),
  ('Kangpokpi', 'Kangpokpi', 'Manipur', 'district'),
  ('Noney', 'Noney', 'Manipur', 'district'),
  ('Pherzawl', 'Pherzawl', 'Manipur', 'district'),
  ('Senapati', 'Senapati', 'Manipur', 'district'),
  ('Tamenglong', 'Tamenglong', 'Manipur', 'district'),
  ('Tengnoupal', 'Tengnoupal', 'Manipur', 'district'),
  ('Thoubal', 'Thoubal', 'Manipur', 'district'),
  ('Ukhrul', 'Ukhrul', 'Manipur', 'district'),
  ('East Garo Hills', 'East Garo Hills', 'Meghalaya', 'district'),
  ('East Jaintia Hills', 'East Jaintia Hills', 'Meghalaya', 'district'),
  ('East Khasi Hills', 'East Khasi Hills', 'Meghalaya', 'district'),
  ('Eastern West Khasi Hills', 'Eastern West Khasi Hills', 'Meghalaya', 'district'),
  ('North Garo Hills', 'North Garo Hills', 'Meghalaya', 'district'),
  ('Ri Bhoi', 'Ri Bhoi', 'Meghalaya', 'district'),
  ('South Garo Hills', 'South Garo Hills', 'Meghalaya', 'district'),
  ('South West Garo Hills', 'South West Garo Hills', 'Meghalaya', 'district'),
  ('South West Khasi Hills', 'South West Khasi Hills', 'Meghalaya', 'district'),
  ('West Garo Hills', 'West Garo Hills', 'Meghalaya', 'district'),
  ('West Jaintia Hills', 'West Jaintia Hills', 'Meghalaya', 'district'),
  ('West Khasi Hills', 'West Khasi Hills', 'Meghalaya', 'district'),
  ('Aizawl', 'Aizawl', 'Mizoram', 'district'),
  ('Champhai', 'Champhai', 'Mizoram', 'district'),
  ('Hnahthial', 'Hnahthial', 'Mizoram', 'district'),
  ('Khawzawl', 'Khawzawl', 'Mizoram', 'district'),
  ('Kolasib', 'Kolasib', 'Mizoram', 'district'),
  ('Lawngtlai', 'Lawngtlai', 'Mizoram', 'district'),
  ('Lunglei', 'Lunglei', 'Mizoram', 'district'),
  ('Mamit', 'Mamit', 'Mizoram', 'district'),
  ('Saitual', 'Saitual', 'Mizoram', 'district'),
  ('Serchhip', 'Serchhip', 'Mizoram', 'district'),
  ('Siaha', 'Siaha', 'Mizoram', 'district'),
  ('Chumoukedima', 'Chumoukedima', 'Nagaland', 'district'),
  ('Dimapur', 'Dimapur', 'Nagaland', 'district'),
  ('Kiphire', 'Kiphire', 'Nagaland', 'district'),
  ('Kohima', 'Kohima', 'Nagaland', 'district'),
  ('Longleng', 'Longleng', 'Nagaland', 'district'),
  ('Meluri', 'Meluri', 'Nagaland', 'district'),
  ('Mokokchung', 'Mokokchung', 'Nagaland', 'district'),
  ('Mon', 'Mon', 'Nagaland', 'district'),
  ('Niuland', 'Niuland', 'Nagaland', 'district'),
  ('Noklak', 'Noklak', 'Nagaland', 'district'),
  ('Peren', 'Peren', 'Nagaland', 'district'),
  ('Phek', 'Phek', 'Nagaland', 'district'),
  ('Shamator', 'Shamator', 'Nagaland', 'district'),
  ('Tseminyu', 'Tseminyu', 'Nagaland', 'district'),
  ('Tuensang', 'Tuensang', 'Nagaland', 'district'),
  ('Wokha', 'Wokha', 'Nagaland', 'district'),
  ('Zunheboto', 'Zunheboto', 'Nagaland', 'district'),
  ('Dhalai', 'Dhalai', 'Tripura', 'district'),
  ('Gomati', 'Gomati', 'Tripura', 'district'),
  ('Khowai', 'Khowai', 'Tripura', 'district'),
  ('North Tripura', 'North Tripura', 'Tripura', 'district'),
  ('Sepahijala', 'Sepahijala', 'Tripura', 'district'),
  ('South Tripura', 'South Tripura', 'Tripura', 'district'),
  ('Unakoti', 'Unakoti', 'Tripura', 'district'),
  ('West Tripura', 'West Tripura', 'Tripura', 'district')
on conflict do nothing;
